// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM0zWugaKdFLlrplXCqBErRsAqAvEcGJQ',
    appId: '1:702437176041:web:14ab4a55cb1f16d4943678',
    messagingSenderId: '702437176041',
    projectId: 'componentesflutter-792c1',
    authDomain: 'componentesflutter-792c1.firebaseapp.com',
    storageBucket: 'componentesflutter-792c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATD3ZfXfFQOa1DVgBPxiN0IjJuwJ_Lros',
    appId: '1:702437176041:android:00e0e8b627c88dac943678',
    messagingSenderId: '702437176041',
    projectId: 'componentesflutter-792c1',
    storageBucket: 'componentesflutter-792c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQdg76f8OAWVZGdu7TcjspyqrG0aOtDes',
    appId: '1:702437176041:ios:444fff21612abd78943678',
    messagingSenderId: '702437176041',
    projectId: 'componentesflutter-792c1',
    storageBucket: 'componentesflutter-792c1.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
